# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-alb-controller-ingress-group
  description: This component provisions a Kubernetes Service that creates an ALB for a specific IngressGroup
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component




